

[[redirects]]
  from = "/productos"
  to = "/index.html"
  status = 200
  

[[redirects]]
  from = "/contacto"
  to = "/index.html"
  status = 200
  

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true