[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200
  force = true



[[redirects]]
  from = "/productos"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/contacto"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/producto/*"
  to = "/producto/:splat"
  status = 200

